//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_DEVOLUCIONES_PROVEEDORES
    {
        public int IdDetalleDevolucionProveedor { get; set; }
        public Nullable<int> IdDevolucionProveedor { get; set; }
        public Nullable<int> IdLote { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> MontoUnitario { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual DEVOLUCIONES_PROVEEDORES DEVOLUCIONES_PROVEEDORES { get; set; }
        public virtual LOTES LOTES { get; set; }
    }
}
