//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRAS
    {
        public int IdDetalleCompra { get; set; }
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdLote { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioCompraUnitario { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
    
        public virtual COMPRAS COMPRAS { get; set; }
        public virtual LOTES LOTES { get; set; }
    }
}
