//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOLUCIONES_PROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVOLUCIONES_PROVEEDORES()
        {
            this.DETALLE_DEVOLUCIONES_PROVEEDORES = new HashSet<DETALLE_DEVOLUCIONES_PROVEEDORES>();
        }
    
        public int IdDevolucionProveedor { get; set; }
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Motivo { get; set; }
        public Nullable<decimal> MontoTotalDevuelto { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual COMPRAS COMPRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_DEVOLUCIONES_PROVEEDORES> DETALLE_DEVOLUCIONES_PROVEEDORES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
