//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOLUCIONES_CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVOLUCIONES_CLIENTES()
        {
            this.DETALLE_DEVOLUCIONES_CLIENTES = new HashSet<DETALLE_DEVOLUCIONES_CLIENTES>();
        }
    
        public int IdDevolucionCliente { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Motivo { get; set; }
        public Nullable<decimal> MontoTotalDevuelto { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_DEVOLUCIONES_CLIENTES> DETALLE_DEVOLUCIONES_CLIENTES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual VENTAS VENTAS { get; set; }
    }
}
