//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DistribuidoraDBEntities : DbContext
    {
        public DistribuidoraDBEntities()
            : base("name=DistribuidoraDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COMPRAS> COMPRAS { get; set; }
        public virtual DbSet<DETALLE_COMPRAS> DETALLE_COMPRAS { get; set; }
        public virtual DbSet<DETALLE_DEVOLUCIONES_CLIENTES> DETALLE_DEVOLUCIONES_CLIENTES { get; set; }
        public virtual DbSet<DETALLE_DEVOLUCIONES_PROVEEDORES> DETALLE_DEVOLUCIONES_PROVEEDORES { get; set; }
        public virtual DbSet<DETALLE_VENTAS> DETALLE_VENTAS { get; set; }
        public virtual DbSet<DEVOLUCIONES_CLIENTES> DEVOLUCIONES_CLIENTES { get; set; }
        public virtual DbSet<DEVOLUCIONES_PROVEEDORES> DEVOLUCIONES_PROVEEDORES { get; set; }
        public virtual DbSet<LABORATORIOS> LABORATORIOS { get; set; }
        public virtual DbSet<LOTES> LOTES { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<PROVEEDORES> PROVEEDORES { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<VENTAS> VENTAS { get; set; }
    }
}
