//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOTES()
        {
            this.DETALLE_COMPRAS = new HashSet<DETALLE_COMPRAS>();
            this.DETALLE_DEVOLUCIONES_CLIENTES = new HashSet<DETALLE_DEVOLUCIONES_CLIENTES>();
            this.DETALLE_DEVOLUCIONES_PROVEEDORES = new HashSet<DETALLE_DEVOLUCIONES_PROVEEDORES>();
            this.DETALLE_VENTAS = new HashSet<DETALLE_VENTAS>();
        }
    
        public int IdLote { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public string NumeroLote { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public int Stock { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioVenta { get; set; }
        public string UbicacionAlmacen { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COMPRAS> DETALLE_COMPRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_DEVOLUCIONES_CLIENTES> DETALLE_DEVOLUCIONES_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_DEVOLUCIONES_PROVEEDORES> DETALLE_DEVOLUCIONES_PROVEEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTAS> DETALLE_VENTAS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
